sonar.projectKey=newshub-frontend
sonar.projectName=newshub-frontend
sonar.projectVersion=1.0.0

# Path to source files
sonar.sources=src
# Path to test files
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts

# Language
sonar.language=ts
sonar.plugin.typescript.node=node_modules/typescript/bin/tsc

# Coverage report path
sonar.typescript.lcov.reportPaths=coverage/newshub-frontend/lcov.info

# Exclusions
sonar.exclusions=**/node_modules/**,**/*.spec.ts,src/environments/**,src/main.ts,src/polyfills.ts
