spring.application.name=newshub
spring.config.import=optional:classpath:application-${spring.profiles.active}.properties

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
