spring.profiles.active=dev

# JWT Configuration
jwt.secret=ThisIsAVeryLongSecretKeyForDevelopmentThatHasAtLeast256BitsOfDataToBeSecure1234567890ABCDEF
jwt.expiration=900000

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/newshub
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Logging
logging.level.root=INFO
logging.level.com.github.arsenmonets.newshub=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping=TRACE

# Admin Configuration
admin.login=admin
admin.password=admin123
admin.email=admin@newshub.com
